<?php

namespace AppBundle\Entity;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;
use Symfony\Component\Config\Definition\Builder\ExprBuilder;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findCatchThemAll($id = null)
    {
        $qb = $this->createQueryBuilder('a');

//        $qb->andWhere(
//        $qb->expr()->like('p.name', '%a%')
//    );

        $qb
            ->select('a, t, c')
            ->leftJoin('a.tag', 't', Expr\Join::WITH)
            ->leftJoin('a.category', 'c', Expr\Join::WITH);

        if (null !== $id) {
            $qb
                ->where('a.id = :id')
                ->setParameters([
                    ':id' => $id,
                ]);
        }


        $qb->orderBy('a.id', 'DESC');

        return null === $id
            ? $qb->getQuery()->getArrayResult()
            : $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY)
            ;
    }


}
